apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: health-api
type: kubernetes.io/dockerconfigjson
data:
  #.dockerconfigjson: <BASE64_ENCODED_DOCKER_CONFIG_JSON> #create base64 using echo -n '{"auths": {"https://index.docker.io/v1/": {"username": "YOUR_USERNAME", "password": "YOUR_TOKEN", "email": "YOUR_EMAIL"}}}' | base64
  .dockerconfigjson: eyJhdXRocyI6IHsiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjogeyJ1c2VybmFtZSI6ICJyaXR1amFlZSIsICJwYXNzd29yZCI6ICJkY2tyX3BhdF9hQ3VSTFdSaWhHS1picUZIZnZUVW5HbmhEbEkiLCAiZW1haWwiOiAicml0dWphLmNoYXVkaGFyaUBlcXVhbGV4cGVydHMuY29tIn19fQ==
